"""Step 41: Player contract event — bounded log of individual obligation/income instances."""

from __future__ import annotations

import uuid

from sqlalchemy import Boolean, Column, Date, DateTime, ForeignKey, Index, Integer, Numeric, String, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db.database import Base


class PlayerContractEvent(Base):
    """Individual recurring obligation or income event.

    Each row represents one due-date instance for a recurring contract obligation
    (rent, utilities, loan payment, insurance, overhead) or an income arrival
    (salary payday, business payout).  status transitions:
      upcoming → due (on due_on_day) → paid | late
      late     → rolled_forward  (when bridge loan covers it a day late)

    Rows are generated by generate_recurring_contracts() and advanced by
    apply_contract_cycle_progression().  Bounded to a forward/backward window
    so the table doesn't grow unboundedly.
    """

    __tablename__ = "player_contract_events"
    __table_args__ = (
        UniqueConstraint(
            "player_id",
            "obligation_key",
            "due_on_day",
            name="uq_pce_player_obligation_day",
        ),
        Index("ix_pce_player_id", "player_id"),
        Index("ix_pce_due_on_day", "due_on_day"),
        Index("ix_pce_status", "status"),
        Index("ix_pce_player_due", "player_id", "due_on_day"),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    player_id = Column(
        UUID(as_uuid=True),
        ForeignKey("players.id", ondelete="CASCADE"),
        nullable=False,
    )

    # --- obligation identity ---
    obligation_key = Column(String(60), nullable=False)
    # e.g. "rent", "utilities", "insurance", "phone", "loan_<loan_id>",
    #      "emergency_loan", "overhead", "salary", "business_payout"
    obligation_family = Column(String(40), nullable=False)
    # personal | debt | business | income
    obligation_type = Column(String(40), nullable=False)
    # rent | utilities | insurance | phone | loan_payment | emergency_loan
    # | overhead | supply | salary | business_payout

    # --- amounts ---
    amount_xgp = Column(Numeric(14, 4), nullable=False, default=0)
    # positive = obligation (outflow); income_flag=True rows have positive amount
    # but represent inflow — the sign convention is kept positive; callers flip

    cycle_days = Column(Integer, nullable=False, default=30)

    # --- timing ---
    due_on_day = Column(Integer, nullable=False)   # game day
    due_on_date = Column(Date, nullable=True)

    # --- status lifecycle ---
    # upcoming | due | paid | late | rolled_forward | waived
    status = Column(String(20), nullable=False, default="upcoming")

    # True = income arrival event (inflow), False = obligation (outflow)
    income_flag = Column(Boolean, nullable=False, default=False)

    # --- resolution ---
    paid_on_day = Column(Integer, nullable=True)
    paid_amount_xgp = Column(Numeric(14, 4), nullable=True)
    resolution_note = Column(String(120), nullable=True)

    # --- optional metadata ---
    source_loan_id = Column(UUID(as_uuid=True), nullable=True)
    # FK to player_loan_accounts.id if this is a loan payment
    debug_notes = Column(Text, nullable=True)

    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    player = relationship("Player", foreign_keys=[player_id])
