"""Expanded deterministic economy event catalog (Step 22).

This module provides static event templates consumed by the event engine.
The catalog intentionally mixes negative/positive/neutral outcomes and
chain-aware metadata so the daily event loop has broader variety while
remaining deterministic and bounded.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class EventTemplate:
    """Single event template used by the deterministic event engine."""

    event_key: str
    headline_template: str
    summary_template: str
    category: str
    sentiment: str
    severity_weight: float
    impact_tags: dict[str, float] = field(default_factory=dict)
    preconditions: dict[str, float] = field(default_factory=dict)
    can_chain: bool = False
    chain_group_key: str = ""
    next_possible_events: tuple[str, ...] = ()
    escalation_events: tuple[str, ...] = ()
    recovery_events: tuple[str, ...] = ()
    max_chain_length: int = 4
    base_continuation_probability: float = 0.0
    decay_per_day: float = 0.15
    severity_escalation_factor: float = 1.15


def _e(
    event_key: str,
    headline: str,
    summary: str,
    category: str,
    sentiment: str,
    severity: float,
    *,
    impact_tags: dict[str, float] | None = None,
    preconditions: dict[str, float] | None = None,
    can_chain: bool = False,
    chain_group_key: str = "",
    next_possible_events: tuple[str, ...] = (),
    escalation_events: tuple[str, ...] = (),
    recovery_events: tuple[str, ...] = (),
    max_chain_length: int = 4,
    base_continuation_probability: float = 0.0,
    decay_per_day: float = 0.15,
    severity_escalation_factor: float = 1.15,
) -> EventTemplate:
    return EventTemplate(
        event_key=event_key,
        headline_template=headline,
        summary_template=summary,
        category=category,
        sentiment=sentiment,
        severity_weight=severity,
        impact_tags=impact_tags or {},
        preconditions=preconditions or {},
        can_chain=can_chain,
        chain_group_key=chain_group_key,
        next_possible_events=next_possible_events,
        escalation_events=escalation_events,
        recovery_events=recovery_events,
        max_chain_length=max_chain_length,
        base_continuation_probability=base_continuation_probability,
        decay_per_day=decay_per_day,
        severity_escalation_factor=severity_escalation_factor,
    )


EVENT_CATALOG: tuple[EventTemplate, ...] = (
    # Energy / fuel chain
    _e(
        "oil_spike",
        "Oil benchmark spikes on refinery and shipping strain",
        "Fuel-sensitive sectors face immediate cost pressure while freight margins tighten.",
        "energy",
        "negative",
        1.65,
        impact_tags={"oil_index": 4.8, "inflation_rate": 0.16, "consumer_confidence": -1.2},
        preconditions={"oil_index_min": 70},
        can_chain=True,
        chain_group_key="energy_shock",
        next_possible_events=("pipeline_disruption", "freight_bottleneck"),
        escalation_events=("refinery_outage", "diesel_shortage"),
        recovery_events=("oil_glut", "supply_relief"),
        max_chain_length=5,
        base_continuation_probability=0.65,
        decay_per_day=0.16,
        severity_escalation_factor=1.22,
    ),
    _e(
        "pipeline_disruption",
        "Regional pipeline disruption delays fuel distribution",
        "Transit and delivery operators report elevated dead-time and route inefficiency.",
        "energy",
        "negative",
        1.42,
        impact_tags={"oil_index": 3.6, "supply_chain_stress": 0.10, "consumer_confidence": -0.7},
        can_chain=True,
        chain_group_key="energy_shock",
        next_possible_events=("freight_bottleneck", "diesel_shortage"),
        escalation_events=("refinery_outage",),
        recovery_events=("oil_glut", "transit_service_upgrade"),
        max_chain_length=5,
        base_continuation_probability=0.60,
    ),
    _e(
        "freight_bottleneck",
        "Freight bottlenecks raise transport lead times",
        "Backlogs build in key lanes, raising delivery uncertainty for retail and food channels.",
        "supply_chain",
        "negative",
        1.36,
        impact_tags={"supply_chain_stress": 0.16, "inflation_rate": 0.10, "oil_index": 1.6},
        can_chain=True,
        chain_group_key="energy_shock",
        next_possible_events=("diesel_shortage", "port_congestion"),
        escalation_events=("refinery_outage",),
        recovery_events=("supply_relief", "local_logistics_optimization"),
        max_chain_length=5,
        base_continuation_probability=0.55,
    ),
    _e(
        "refinery_outage",
        "Refinery outage compounds fuel and logistics pressure",
        "Input costs rise broadly as distribution slack disappears across multiple sectors.",
        "energy",
        "negative",
        1.78,
        impact_tags={"oil_index": 5.4, "inflation_rate": 0.18, "supply_chain_stress": 0.08},
        can_chain=True,
        chain_group_key="energy_shock",
        next_possible_events=("diesel_shortage", "port_congestion"),
        escalation_events=(),
        recovery_events=("oil_glut", "supply_relief"),
        max_chain_length=4,
        base_continuation_probability=0.48,
    ),
    _e(
        "diesel_shortage",
        "Diesel shortage pushes delivery costs higher",
        "Commuters and freight operators absorb higher daily operating burdens.",
        "energy",
        "negative",
        1.45,
        impact_tags={"oil_index": 3.2, "inflation_rate": 0.11, "consumer_confidence": -0.8},
        can_chain=True,
        chain_group_key="energy_shock",
        next_possible_events=("port_congestion", "suburban_commute_crunch"),
        escalation_events=(),
        recovery_events=("oil_glut", "fuel_tax_relief"),
        max_chain_length=4,
        base_continuation_probability=0.44,
    ),
    _e(
        "oil_glut",
        "Oil supply glut eases transport cost pressure",
        "Fuel-sensitive sectors regain margin room and inflation pressure cools modestly.",
        "recovery",
        "positive",
        1.10,
        impact_tags={"oil_index": -4.2, "inflation_rate": -0.10, "consumer_confidence": 0.8},
    ),
    _e(
        "fuel_tax_relief",
        "Temporary fuel tax relief lowers transport burden",
        "Daily commute and delivery economics improve with a short-term buffer.",
        "recovery",
        "positive",
        0.98,
        impact_tags={"oil_index": -1.8, "consumer_confidence": 0.7},
    ),
    _e(
        "transit_efficiency_push",
        "Transit efficiency push reduces route dead-time",
        "Faster cycle times soften logistics drag in dense corridors.",
        "recovery",
        "positive",
        0.92,
        impact_tags={"supply_chain_stress": -0.07, "consumer_confidence": 0.5},
    ),

    # Logistics / supply chains
    _e(
        "port_congestion",
        "Port congestion extends import lead times",
        "Retail and food restocking windows widen as throughput slows.",
        "supply_chain",
        "negative",
        1.34,
        impact_tags={"supply_chain_stress": 0.22, "inflation_rate": 0.08},
        can_chain=True,
        chain_group_key="logistics_wave",
        next_possible_events=("customs_backlog", "rail_delay"),
        escalation_events=("warehouse_overflow",),
        recovery_events=("supply_relief", "import_clearance_surge"),
        max_chain_length=5,
        base_continuation_probability=0.60,
    ),
    _e(
        "customs_backlog",
        "Customs backlog slows critical goods clearance",
        "Delays raise holding costs and planning uncertainty for operators.",
        "supply_chain",
        "negative",
        1.22,
        impact_tags={"supply_chain_stress": 0.14, "inflation_rate": 0.07},
        can_chain=True,
        chain_group_key="logistics_wave",
        next_possible_events=("rail_delay", "warehouse_overflow"),
        escalation_events=(),
        recovery_events=("import_clearance_surge", "supply_relief"),
        max_chain_length=4,
        base_continuation_probability=0.53,
    ),
    _e(
        "rail_delay",
        "Rail corridor delays disrupt inland replenishment",
        "Transit latency grows for produce and essentials distribution.",
        "supply_chain",
        "negative",
        1.16,
        impact_tags={"supply_chain_stress": 0.12, "consumer_confidence": -0.4},
        can_chain=True,
        chain_group_key="logistics_wave",
        next_possible_events=("warehouse_overflow", "utility_strain_alert"),
        escalation_events=(),
        recovery_events=("local_logistics_optimization", "supply_relief"),
        max_chain_length=4,
        base_continuation_probability=0.50,
    ),
    _e(
        "warehouse_overflow",
        "Warehouse overflow raises handling inefficiencies",
        "Overstock and slotting pressure increase shrink and routing errors.",
        "supply_chain",
        "neutral",
        0.92,
        impact_tags={"supply_chain_stress": 0.07, "consumer_confidence": -0.2},
    ),
    _e(
        "container_repricing",
        "Container repricing pushes import handling costs",
        "Repricing pressure is visible in midstream inventory channels.",
        "supply_chain",
        "negative",
        1.00,
        impact_tags={"inflation_rate": 0.06, "supply_chain_stress": 0.06},
    ),
    _e(
        "supply_relief",
        "Supply bottlenecks ease as routing normalizes",
        "Distribution cadence improves and short-term inflation pressure cools.",
        "recovery",
        "positive",
        1.15,
        impact_tags={"supply_chain_stress": -0.18, "inflation_rate": -0.08, "consumer_confidence": 0.7},
    ),
    _e(
        "import_clearance_surge",
        "Import clearance surge shortens backlogs",
        "Throughput improvements reduce restock uncertainty for small operators.",
        "recovery",
        "positive",
        1.02,
        impact_tags={"supply_chain_stress": -0.11, "consumer_confidence": 0.4},
    ),
    _e(
        "local_logistics_optimization",
        "Local logistics optimization improves fill rates",
        "Route smoothing and better staging improve operating reliability.",
        "recovery",
        "positive",
        0.96,
        impact_tags={"supply_chain_stress": -0.09, "inflation_rate": -0.04},
    ),

    # Food supply / utility / maintenance pressures
    _e(
        "produce_blight_warning",
        "Produce blight warning reduces near-term yield outlook",
        "Fresh produce channels price in spoilage and replacement risk.",
        "food_supply",
        "negative",
        1.18,
        impact_tags={"inflation_rate": 0.09, "consumer_confidence": -0.4, "supply_chain_stress": 0.05},
        can_chain=True,
        chain_group_key="food_pressure",
        next_possible_events=("cold_storage_failure", "protein_shortfall"),
        escalation_events=(),
        recovery_events=("harvest_rebound", "local_farm_coop_boost"),
        max_chain_length=4,
        base_continuation_probability=0.45,
    ),
    _e(
        "cold_storage_failure",
        "Cold storage disruption increases food wastage pressure",
        "Perishables face higher spoilage risk and tighter replenishment windows.",
        "food_supply",
        "negative",
        1.14,
        impact_tags={"supply_chain_stress": 0.10, "inflation_rate": 0.07},
    ),
    _e(
        "protein_shortfall",
        "Protein supply shortfall tightens menu economics",
        "Food operators absorb volatility in core ingredient costs.",
        "food_supply",
        "negative",
        1.08,
        impact_tags={"inflation_rate": 0.08, "consumer_confidence": -0.3},
    ),
    _e(
        "harvest_rebound",
        "Harvest rebound improves produce availability",
        "Fresh inventory costs stabilize as regional yields recover.",
        "recovery",
        "positive",
        0.94,
        impact_tags={"inflation_rate": -0.05, "supply_chain_stress": -0.04, "consumer_confidence": 0.4},
    ),
    _e(
        "local_farm_coop_boost",
        "Local farm co-op contracts improve resilience",
        "Shorter procurement paths reduce fragility in produce supply.",
        "recovery",
        "positive",
        0.90,
        impact_tags={"supply_chain_stress": -0.05, "consumer_confidence": 0.3},
    ),
    _e(
        "utility_strain_alert",
        "Utility strain alert raises operating caution",
        "Cooling and prep operations face intermittent disruption risk.",
        "utility_strain",
        "negative",
        0.98,
        impact_tags={"consumer_confidence": -0.4, "inflation_rate": 0.03},
    ),
    _e(
        "grid_maintenance_disruption",
        "Grid maintenance windows disrupt operating schedules",
        "Small operators absorb workflow inefficiency during scheduled outages.",
        "maintenance_safety",
        "negative",
        0.94,
        impact_tags={"consumer_confidence": -0.3, "supply_chain_stress": 0.03},
    ),
    _e(
        "maintenance_grant_program",
        "Maintenance grant program lowers downtime risk",
        "Targeted support improves reliability in critical local infrastructure.",
        "recovery",
        "positive",
        0.86,
        impact_tags={"consumer_confidence": 0.4, "supply_chain_stress": -0.03},
    ),
    _e(
        "safety_inspection_sweep",
        "Safety inspection sweep slows operations temporarily",
        "Short-term compliance friction trades speed for lower disruption risk later.",
        "maintenance_safety",
        "neutral",
        0.82,
        impact_tags={"supply_chain_stress": 0.02},
    ),

    # Labor / job market conditions
    _e(
        "layoff_wave",
        "Layoff wave hits multiple service sectors",
        "Households turn cautious as hiring pipelines weaken and labor slack rises.",
        "labor",
        "negative",
        1.58,
        impact_tags={"unemployment_rate": 0.35, "consumer_confidence": -1.6},
        can_chain=True,
        chain_group_key="labor_slump",
        next_possible_events=("hiring_freeze", "retail_slump"),
        escalation_events=("wage_pressure_jump",),
        recovery_events=("hiring_surge", "confidence_rebound"),
        max_chain_length=5,
        base_continuation_probability=0.62,
        severity_escalation_factor=1.20,
    ),
    _e(
        "hiring_freeze",
        "Hiring freeze limits near-term opportunity access",
        "Openings slow in entry and mid-skill lanes across several sectors.",
        "labor",
        "negative",
        1.26,
        impact_tags={"unemployment_rate": 0.20, "consumer_confidence": -0.9},
        can_chain=True,
        chain_group_key="labor_slump",
        next_possible_events=("retail_slump", "consumer_pullback"),
        escalation_events=("layoff_wave",),
        recovery_events=("hiring_surge",),
        max_chain_length=4,
        base_continuation_probability=0.54,
    ),
    _e(
        "wage_pressure_jump",
        "Wage pressure jumps in high-turnover roles",
        "Employers absorb payroll drag while pass-through pricing pressure rises.",
        "labor",
        "negative",
        1.07,
        impact_tags={"inflation_rate": 0.08, "unemployment_rate": -0.08},
    ),
    _e(
        "overtime_reliance",
        "Firms lean on overtime to cover labor gaps",
        "Productivity holds short-term but burnout risk rises in shift-heavy roles.",
        "labor",
        "neutral",
        0.90,
        impact_tags={"consumer_confidence": -0.2},
    ),
    _e(
        "hiring_surge",
        "Hiring surge improves job access and wage confidence",
        "Labor demand broadens and unemployment pressure eases.",
        "recovery",
        "positive",
        1.22,
        impact_tags={"unemployment_rate": -0.28, "consumer_confidence": 1.4},
    ),
    _e(
        "apprenticeship_push",
        "Apprenticeship push expands skill-entry pathways",
        "Career ladders become slightly more accessible for upskilling workers.",
        "labor",
        "positive",
        0.88,
        impact_tags={"unemployment_rate": -0.06, "consumer_confidence": 0.5},
    ),
    _e(
        "union_settlement",
        "Union settlement stabilizes staffing in key services",
        "Scheduling risk cools while wage expectations normalize.",
        "labor",
        "positive",
        0.86,
        impact_tags={"consumer_confidence": 0.4, "supply_chain_stress": -0.02},
    ),

    # Consumer demand / retail cycles
    _e(
        "consumer_pullback",
        "Consumer spending pulls back amid confidence dip",
        "Households prioritize essentials while discretionary demand softens.",
        "consumer",
        "negative",
        1.44,
        impact_tags={"consumer_confidence": -1.8, "inflation_rate": -0.04},
        preconditions={"consumer_confidence_max": 60},
        can_chain=True,
        chain_group_key="demand_softness",
        next_possible_events=("retail_slump", "credit_tightening"),
        escalation_events=("discretionary_spending_shift",),
        recovery_events=("confidence_rebound", "local_festival_boost"),
        max_chain_length=5,
        base_continuation_probability=0.58,
    ),
    _e(
        "retail_slump",
        "Retail demand slump weighs on service-sector momentum",
        "Traffic and basket sizes soften in non-essential categories.",
        "consumer",
        "negative",
        1.28,
        impact_tags={"consumer_confidence": -1.1, "unemployment_rate": 0.12},
        can_chain=True,
        chain_group_key="demand_softness",
        next_possible_events=("discount_cycle", "credit_tightening"),
        escalation_events=("consumer_pullback",),
        recovery_events=("confidence_rebound",),
        max_chain_length=4,
        base_continuation_probability=0.52,
    ),
    _e(
        "discretionary_spending_shift",
        "Spending mix shifts toward essentials",
        "Premium discretionary categories underperform while basics stay resilient.",
        "consumer",
        "neutral",
        0.92,
        impact_tags={"consumer_confidence": -0.5},
    ),
    _e(
        "discount_cycle",
        "Discount cycle boosts volume but compresses margins",
        "Price-sensitive demand returns with softer average ticket values.",
        "consumer",
        "neutral",
        0.94,
        impact_tags={"consumer_confidence": 0.3, "inflation_rate": -0.03},
    ),
    _e(
        "confidence_rebound",
        "Consumer confidence rebounds on improving outlook",
        "Household sentiment stabilizes and demand conditions improve.",
        "recovery",
        "positive",
        1.20,
        impact_tags={"consumer_confidence": 1.6, "unemployment_rate": -0.08},
    ),
    _e(
        "local_festival_boost",
        "Regional festival week lifts local traffic and demand",
        "Retail and food traffic strengthen as footfall rises.",
        "regional_traffic",
        "positive",
        0.95,
        impact_tags={"consumer_confidence": 0.8},
    ),
    _e(
        "tourism_uptick",
        "Tourism uptick raises downtown transaction flow",
        "Visitor-driven demand supports short-run service revenues.",
        "regional_traffic",
        "positive",
        0.90,
        impact_tags={"consumer_confidence": 0.6},
    ),

    # Financial / credit conditions
    _e(
        "credit_tightening",
        "Banks tighten credit standards for households and small firms",
        "Financing access narrows and risk pricing rises for marginal borrowers.",
        "financial",
        "negative",
        1.35,
        impact_tags={"interest_rate": 0.10, "consumer_confidence": -1.0},
        can_chain=True,
        chain_group_key="credit_cycle",
        next_possible_events=("small_business_lending_squeeze", "delinquency_warning"),
        escalation_events=(),
        recovery_events=("bank_liquidity_support", "debt_refinance_window"),
        max_chain_length=5,
        base_continuation_probability=0.56,
    ),
    _e(
        "small_business_lending_squeeze",
        "Small-business lending squeeze raises growth friction",
        "Expansion plans slow as borrowing terms become more conservative.",
        "financial",
        "negative",
        1.10,
        impact_tags={"interest_rate": 0.08, "consumer_confidence": -0.5},
    ),
    _e(
        "delinquency_warning",
        "Rising delinquency warnings increase risk aversion",
        "Lenders and households both shift toward defensive balance-sheet behavior.",
        "financial",
        "negative",
        1.04,
        impact_tags={"interest_rate": 0.05, "consumer_confidence": -0.7},
    ),
    _e(
        "policy_hold",
        "Policy hold keeps rates and guidance steady",
        "Markets digest a stable policy stance with mixed near-term implications.",
        "financial",
        "neutral",
        0.86,
        impact_tags={"interest_rate": 0.00},
    ),
    _e(
        "rate_cut_signal",
        "Rate-cut signal improves financing sentiment",
        "Borrowing outlook softens modestly, helping confidence-sensitive sectors.",
        "financial",
        "positive",
        0.96,
        impact_tags={"interest_rate": -0.07, "consumer_confidence": 0.8},
    ),
    _e(
        "bank_liquidity_support",
        "Liquidity support eases short-term credit constraints",
        "Funding conditions stabilize for households and small operators.",
        "recovery",
        "positive",
        0.98,
        impact_tags={"interest_rate": -0.05, "consumer_confidence": 0.6},
    ),
    _e(
        "household_savings_drawdown",
        "Household savings drawdown signals weaker cushion",
        "Consumers remain active but become more exposed to shocks.",
        "financial",
        "negative",
        0.92,
        impact_tags={"consumer_confidence": -0.4},
    ),
    _e(
        "debt_refinance_window",
        "Debt refinance window opens for qualified borrowers",
        "Payment pressure eases incrementally where credit conditions permit.",
        "recovery",
        "positive",
        0.88,
        impact_tags={"interest_rate": -0.04, "consumer_confidence": 0.5},
    ),

    # Regional traffic / commuting / setup-neutrals
    _e(
        "downtown_road_closure",
        "Downtown road closure increases travel friction",
        "Commute and delivery schedules face temporary congestion drag.",
        "regional_traffic",
        "negative",
        0.96,
        impact_tags={"oil_index": 0.9, "consumer_confidence": -0.3},
    ),
    _e(
        "suburban_commute_crunch",
        "Suburban commute crunch raises travel time volatility",
        "Longer commutes reduce effective discretionary hours for some households.",
        "regional_traffic",
        "negative",
        0.92,
        impact_tags={"oil_index": 0.7, "consumer_confidence": -0.2},
    ),
    _e(
        "downtown_event_week",
        "Downtown event week boosts dense-area foot traffic",
        "Demand density improves in transit-connected commercial corridors.",
        "regional_traffic",
        "positive",
        0.88,
        impact_tags={"consumer_confidence": 0.5},
    ),
    _e(
        "transit_service_upgrade",
        "Transit service upgrade trims daily commute friction",
        "Reliability gains support better opportunity access in busy zones.",
        "regional_traffic",
        "positive",
        0.84,
        impact_tags={"consumer_confidence": 0.4, "oil_index": -0.4},
    ),
    _e(
        "mixed_signals",
        "Mixed signals keep the economy in wait-and-see mode",
        "No dominant shock emerges; households and firms stay cautious but active.",
        "consumer",
        "neutral",
        0.75,
        impact_tags={"consumer_confidence": 0.0},
    ),
    _e(
        "seasonal_adjustment",
        "Seasonal adjustment nudges demand patterns",
        "Routine seasonal effects shift timing rather than trend direction.",
        "consumer",
        "neutral",
        0.78,
        impact_tags={"consumer_confidence": 0.2, "supply_chain_stress": -0.02},
    ),
)


EVENT_CATALOG_BY_KEY: dict[str, EventTemplate] = {event.event_key: event for event in EVENT_CATALOG}

NEGATIVE_KEYS: tuple[str, ...] = tuple(
    event.event_key for event in EVENT_CATALOG if event.sentiment == "negative"
)
POSITIVE_KEYS: tuple[str, ...] = tuple(
    event.event_key for event in EVENT_CATALOG if event.sentiment == "positive"
)
NEUTRAL_KEYS: tuple[str, ...] = tuple(
    event.event_key for event in EVENT_CATALOG if event.sentiment == "neutral"
)

