"""add_fk_constraints

Revision ID: 85854026afad
Revises: 20260316_0002_enable_rls
Create Date: 2026-03-15 21:09:24.675744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85854026afad'
down_revision: Union[str, Sequence[str], None] = '20260316_0002_enable_rls'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('basket_daily_prices', 'daily_change_pct',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('basket_daily_prices', 'supply_pressure',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('basket_daily_prices', 'demand_pressure',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'coop_deal_participants', 'coop_deals', ['deal_id'], ['id'])
    op.create_foreign_key(None, 'coop_deal_payouts', 'coop_deals', ['deal_id'], ['id'])
    op.alter_column('daily_settlement_logs', 'hours_before_reset',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'hours_after_reset',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'stress_before',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'stress_after',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'health_before',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'health_after',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'cash_before',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'cash_after',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'income_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'expenses_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'stock_pnl_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'debt_paid_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'health_change',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'stress_change',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'recovery_applied',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'needs_score',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'food_quality_modifier',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'stress_penalty_from_needs',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'health_modifier_from_needs',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'housing_cost_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'housing_stress_modifier',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'side_income_hours',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'side_income_net_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'debt_accounts', 'players', ['player_id'], ['id'])
    op.create_foreign_key(None, 'employment_contracts', 'firms', ['firm_id'], ['id'])
    op.create_foreign_key(None, 'firm_balance_snapshots', 'firms', ['firm_id'], ['id'])
    op.create_foreign_key(None, 'firm_capacities', 'firms', ['firm_id'], ['id'])
    op.create_foreign_key(None, 'firm_ledger_entries', 'firms', ['firm_id'], ['id'])
    op.create_foreign_key(None, 'firm_policies', 'firms', ['firm_id'], ['id'])
    op.alter_column('job_definitions', 'stability_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_definitions', 'growth_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_definitions', 'stress_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_definitions', 'promotion_threshold',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # Drop dependent FK first so we can drop+recreate the unique constraint
    op.drop_constraint('player_employment_states_current_job_code_fkey', 'player_employment_states', type_='foreignkey')
    op.drop_constraint(op.f('uq_job_definitions_job_code'), 'job_definitions', type_='unique')
    op.create_foreign_key(None, 'job_openings', 'firms', ['firm_id'], ['id'], ondelete='SET NULL')
    op.alter_column('macro_daily_states', 'inflation_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('macro_daily_states', 'interest_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('macro_daily_states', 'unemployment_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('macro_daily_states', 'oil_index',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('macro_daily_states', 'consumer_confidence',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('macro_daily_states', 'supply_chain_stress',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_macro_daily_states_day'), 'macro_daily_states', type_='unique')
    op.drop_index(op.f('ix_macro_daily_states_day'), table_name='macro_daily_states')
    op.create_index(op.f('ix_macro_daily_states_day'), 'macro_daily_states', ['day'], unique=True)
    op.alter_column('player_daily_states', 'hours_available_start',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'hours_available_end',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'worked_main_job',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'worked_hours',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'gross_income_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'did_settlement',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'stress_start',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'stress_end',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'health_start',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'health_end',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'cash_start',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'cash_end',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'essentials_units',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'protein_units',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'produce_units',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'convenience_units',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'total_spent_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'debt_payment_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'stock_realized_pnl_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'needs_score',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'needs_evaluated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'food_quality_score',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'survival_coverage_score',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'housing_cost_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'side_income_hours',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'side_income_gross_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'side_income_fuel_cost_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_daily_states', 'side_income_net_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_employment_states', 'skill_level',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_employment_states', 'monthly_pay_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_employment_states', 'employed_flag',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_employment_states', 'layoff_risk_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_employment_states', 'productivity_modifier',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_stock_holdings', 'shares_owned',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_stock_holdings', 'average_cost_basis',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('player_stock_holdings', 'total_cost_basis',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'cash',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'bank_savings_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'debt_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'credit_score',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'reputation',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'health',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'stress',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'fatigue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'skill_level',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'hours_available',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'main_job_hours_today',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'side_job_hours_today',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'total_hours_worked_today',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'work_actions_today',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'region',
               existing_type=sa.VARCHAR(length=40),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'net_worth',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'housing_stability',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'has_active_housing',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'pending_reward_points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'pending_token_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'total_lifetime_token_claimed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'reward_eligibility_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'anti_cheat_flag',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'wallet_linked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'lifetime_xgp_earned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'lifetime_contribution_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'is_reward_eligible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'completed_trades_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'marketplace_rating_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'successful_coop_deals_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('players', 'failed_coop_deals_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_players_user_id'), 'players', type_='unique')
    op.alter_column('stock_daily_prices', 'macro_impact',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_daily_prices', 'noise_component',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('stock_daily_prices', 'noise_component',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('stock_daily_prices', 'macro_impact',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_players_user_id'), 'players', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('players', 'failed_coop_deals_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('players', 'successful_coop_deals_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('players', 'marketplace_rating_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('players', 'completed_trades_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('players', 'is_reward_eligible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('players', 'lifetime_contribution_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('players', 'lifetime_xgp_earned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('players', 'wallet_linked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('players', 'anti_cheat_flag',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('players', 'reward_eligibility_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'eligible'::character varying"),
               existing_nullable=False)
    op.alter_column('players', 'total_lifetime_token_claimed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('players', 'pending_token_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('players', 'pending_reward_points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('players', 'has_active_housing',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('players', 'housing_stability',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.alter_column('players', 'net_worth',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text("'1000'::numeric"),
               existing_nullable=False)
    op.alter_column('players', 'region',
               existing_type=sa.VARCHAR(length=40),
               server_default=sa.text("'suburban'::character varying"),
               existing_nullable=False)
    op.alter_column('players', 'work_actions_today',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('players', 'total_hours_worked_today',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('players', 'side_job_hours_today',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('players', 'main_job_hours_today',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('players', 'hours_available',
               existing_type=sa.INTEGER(),
               server_default=sa.text('16'),
               existing_nullable=False)
    op.alter_column('players', 'skill_level',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('players', 'fatigue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('players', 'stress',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('players', 'health',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.alter_column('players', 'reputation',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('players', 'credit_score',
               existing_type=sa.INTEGER(),
               server_default=sa.text('650'),
               existing_nullable=False)
    op.alter_column('players', 'debt_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('players', 'bank_savings_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('players', 'cash',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'1000'::numeric"),
               existing_nullable=False)
    op.alter_column('player_stock_holdings', 'total_cost_basis',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_stock_holdings', 'average_cost_basis',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_stock_holdings', 'shares_owned',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('player_employment_states', 'productivity_modifier',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text('1.0'),
               existing_nullable=False)
    op.alter_column('player_employment_states', 'layoff_risk_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_employment_states', 'employed_flag',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('player_employment_states', 'monthly_pay_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_employment_states', 'skill_level',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'side_income_net_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'side_income_fuel_cost_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'side_income_gross_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'side_income_hours',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'housing_cost_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'survival_coverage_score',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'food_quality_score',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'needs_evaluated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'needs_score',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'stock_realized_pnl_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'debt_payment_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'total_spent_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'convenience_units',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'produce_units',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'protein_units',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'essentials_units',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'cash_end',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'cash_start',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'health_end',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'health_start',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'stress_end',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'stress_start',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'did_settlement',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'gross_income_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'worked_hours',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'worked_main_job',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'hours_available_end',
               existing_type=sa.INTEGER(),
               server_default=sa.text('24'),
               existing_nullable=False)
    op.alter_column('player_daily_states', 'hours_available_start',
               existing_type=sa.INTEGER(),
               server_default=sa.text('24'),
               existing_nullable=False)
    op.drop_index(op.f('ix_macro_daily_states_day'), table_name='macro_daily_states')
    op.create_index(op.f('ix_macro_daily_states_day'), 'macro_daily_states', ['day'], unique=False)
    op.create_unique_constraint(op.f('uq_macro_daily_states_day'), 'macro_daily_states', ['day'], postgresql_nulls_not_distinct=False)
    op.alter_column('macro_daily_states', 'supply_chain_stress',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.alter_column('macro_daily_states', 'consumer_confidence',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text('50.0'),
               existing_nullable=False)
    op.alter_column('macro_daily_states', 'oil_index',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               server_default=sa.text('100.0'),
               existing_nullable=False)
    op.alter_column('macro_daily_states', 'unemployment_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text('5.0'),
               existing_nullable=False)
    op.alter_column('macro_daily_states', 'interest_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text('4.0'),
               existing_nullable=False)
    op.alter_column('macro_daily_states', 'inflation_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text('2.0'),
               existing_nullable=False)
    op.drop_constraint(None, 'job_openings', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_job_definitions_job_code'), 'job_definitions', ['job_code'], postgresql_nulls_not_distinct=False)
    # Restore the FK that depended on the unique constraint
    op.create_foreign_key('player_employment_states_current_job_code_fkey', 'player_employment_states', 'job_definitions', ['current_job_code'], ['job_code'])
    op.alter_column('job_definitions', 'promotion_threshold',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.alter_column('job_definitions', 'stress_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('job_definitions', 'growth_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('job_definitions', 'stability_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.drop_constraint(None, 'firm_policies', type_='foreignkey')
    op.drop_constraint(None, 'firm_ledger_entries', type_='foreignkey')
    op.drop_constraint(None, 'firm_capacities', type_='foreignkey')
    op.drop_constraint(None, 'firm_balance_snapshots', type_='foreignkey')
    op.drop_constraint(None, 'employment_contracts', type_='foreignkey')
    op.drop_constraint(None, 'debt_accounts', type_='foreignkey')
    op.alter_column('daily_settlement_logs', 'side_income_net_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'side_income_hours',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'housing_stress_modifier',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'housing_cost_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'health_modifier_from_needs',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'stress_penalty_from_needs',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'food_quality_modifier',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'needs_score',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'recovery_applied',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'stress_change',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'health_change',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'debt_paid_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'stock_pnl_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'expenses_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'income_xgp',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'cash_after',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'cash_before',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'health_after',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'health_before',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'stress_after',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'stress_before',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'hours_after_reset',
               existing_type=sa.INTEGER(),
               server_default=sa.text('24'),
               existing_nullable=False)
    op.alter_column('daily_settlement_logs', 'hours_before_reset',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'coop_deal_payouts', type_='foreignkey')
    op.drop_constraint(None, 'coop_deal_participants', type_='foreignkey')
    op.alter_column('basket_daily_prices', 'demand_pressure',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text('1.0'),
               existing_nullable=False)
    op.alter_column('basket_daily_prices', 'supply_pressure',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text('1.0'),
               existing_nullable=False)
    op.alter_column('basket_daily_prices', 'daily_change_pct',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    # ### end Alembic commands ###
