"""app/engine/coop_deal_engine.py — Step 13: Co-op Deals System.

Co-op deals are structured collaboration opportunities generated by the system.
Players fill predefined roles using their jobs or businesses.  Fixed split
presets distribute payout deterministically — no freeform negotiation.

This is the first true cooperative layer of the Gold Penny economy.  Until
Step 13, all gameplay was player-vs-system.  Co-op deals introduce:
  - Role-based social matching (your job matters to other players)
  - Collective upside (final payout scales with macro economy health)
  - Trust signals (reputation modestly increments on successful collaboration)
  - Contribution scoring (co-op activity feeds the PFT reward engine)

Role-matching rules (deterministic):
  "chef"            — player.main_job == "chef"
  "delivery_driver" — player.main_job == "delivery_driver"
  "auto_mechanic"   — player.main_job == "auto_mechanic"
  "retail_worker"   — player.main_job == "retail_worker"
  "fruit_shop_owner"— player owns an active PlayerBusiness with business_id="fruit_shop"

Payout formula:
  multiplier = clamp(1 + confidence_boost + basket_pressure, 0.80, 1.35)
  confidence_boost = ((consumer_confidence - 50) / 100) × confidence_sensitivity
  basket_pressure  = mean weighted deviation of basket prices from baseline (1.0)
  final_payout     = round(base_payout × multiplier, 2)

Sample lifecycle (Day 18):
  1. Player A (chef) creates "Weekend Festival Food Rush" with split [50, 50].
  2. Player A is auto-assigned to the "chef" role.
  3. Player B (delivery_driver) joins — fills the second role.
  4. Deal transitions to status "filled" automatically.
  5. Complete call is made → final payout calculated from macro state.
  6. XGP split 50 / 50; both players gain +1 reputation.
  7. CoopDealPayout + XGPTransaction rows written for full audit trail.

Unfilled deal example:
  Host creates "Mechanic Rush Contract".  No delivery_driver joins before
  expires_day_number arrives.  expire_open_deals() sets status = "expired".
  Host failed_coop_deals_count increments.  No payout occurs.
"""

from __future__ import annotations

import json
from decimal import ROUND_HALF_UP, Decimal
from typing import Any

from sqlalchemy.orm import Session

from app.models.coop_deal import CoopDeal
from app.models.coop_deal_participant import CoopDealParticipant
from app.models.coop_deal_payout import CoopDealPayout
from app.models.contribution_event import ContributionEvent
from app.models.deal_template import DealTemplate
from app.models.game_state import GameState
from app.models.macro_state import MacroState
from app.models.player import Player
from app.models.player_business import PlayerBusiness
from app.models.xgp_transaction import XGPTransaction

# ── Monetary helper ────────────────────────────────────────────────────────────


def _money(val: Any) -> Decimal:
    return Decimal(str(val)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def _current_day(db: Session) -> int:
    state = db.query(GameState).order_by(GameState.id.asc()).first()
    return int(state.current_day) if state else 1


# ── Default template definitions ───────────────────────────────────────────────

_DEFAULT_TEMPLATES: list[dict] = [
    {
        "template_id": "festival_food_rush",
        "display_name": "Weekend Festival Food Rush",
        "description": (
            "A local festival needs a chef and a delivery driver working together. "
            "High-demand downtown event — basket price pressure boosts the payout."
        ),
        "required_roles_json": json.dumps(["chef", "delivery_driver"]),
        "allowed_split_presets_json": json.dumps([[50, 50], [60, 40], [40, 60]]),
        "base_payout_xgp": 120.0,
        "hours_required_per_participant": 3,
        "region_bias": "downtown",
        "confidence_sensitivity": 0.25,
        "basket_dependency_json": json.dumps({"protein": 1.0, "essentials": 0.5}),
    },
    {
        "template_id": "produce_shortage_opportunity",
        "display_name": "Produce Shortage Opportunity",
        "description": (
            "A regional produce shortage creates a profitable gap for fruit shop owners. "
            "Solo opportunity — full payout to one qualifying player."
        ),
        "required_roles_json": json.dumps(["fruit_shop_owner"]),
        "allowed_split_presets_json": json.dumps([[100]]),
        "base_payout_xgp": 90.0,
        "hours_required_per_participant": 3,
        "region_bias": None,
        "confidence_sensitivity": 0.10,
        "basket_dependency_json": json.dumps({"produce": 1.0}),
    },
    {
        "template_id": "mechanic_rush_contract",
        "display_name": "Mechanic Rush Contract",
        "description": (
            "A fleet manager needs a mechanic and a driver to service multiple vehicles. "
            "Flexible split options available — choose your preset at deal creation."
        ),
        "required_roles_json": json.dumps(["auto_mechanic", "delivery_driver"]),
        "allowed_split_presets_json": json.dumps([[50, 50], [65, 35], [35, 65]]),
        "base_payout_xgp": 110.0,
        "hours_required_per_participant": 2,
        "region_bias": None,
        "confidence_sensitivity": 0.05,
        "basket_dependency_json": None,
    },
    {
        "template_id": "retail_surge_contract",
        "display_name": "Retail Surge Contract",
        "description": (
            "Downtown retail demand surge — a retail worker and delivery driver "
            "collaborate to fulfil high-velocity orders."
        ),
        "required_roles_json": json.dumps(["retail_worker", "delivery_driver"]),
        "allowed_split_presets_json": json.dumps([[50, 50], [60, 40], [40, 60]]),
        "base_payout_xgp": 95.0,
        "hours_required_per_participant": 2,
        "region_bias": "downtown",
        "confidence_sensitivity": 0.15,
        "basket_dependency_json": None,
    },
]

# ── Template seeding ───────────────────────────────────────────────────────────


def get_or_seed_default_deal_templates(db: Session) -> list[DealTemplate]:
    """Seed the 4 default deal templates if missing.  Return all active templates.

    Idempotent — safe to call on every startup without creating duplicates.
    Existing rows are left untouched; only truly missing template_ids are added.
    """
    for spec in _DEFAULT_TEMPLATES:
        existing = (
            db.query(DealTemplate)
            .filter(DealTemplate.template_id == spec["template_id"])
            .first()
        )
        if existing is None:
            db.add(DealTemplate(**spec))
    db.commit()
    return (
        db.query(DealTemplate)
        .filter(DealTemplate.is_active.is_(True))
        .order_by(DealTemplate.id.asc())
        .all()
    )


# ── Role qualification ─────────────────────────────────────────────────────────


def player_qualifies_for_role(
    player: Player,
    role_id: str,
    player_business: PlayerBusiness | None = None,
) -> bool:
    """Return True if the player qualifies for role_id.

    Job-based roles map directly to player.main_job (case-insensitive strip).
    Business-based roles require an active matching PlayerBusiness row.

    Deterministic — no randomness, no side effects.

    Supported roles:
      "chef"            — player.main_job == "chef"
      "delivery_driver" — player.main_job == "delivery_driver"
      "auto_mechanic"   — player.main_job == "auto_mechanic"
      "retail_worker"   — player.main_job == "retail_worker"
      "fruit_shop_owner"— active PlayerBusiness with business_id == "fruit_shop"

    Unknown roles always return False (deny-by-default; forward-compatible).
    """
    job_roles: frozenset[str] = frozenset({
        "chef",
        "delivery_driver",
        "auto_mechanic",
        "retail_worker",
    })

    if role_id in job_roles:
        return (player.main_job or "").strip().lower() == role_id.lower()

    if role_id == "fruit_shop_owner":
        if player_business is None:
            return False
        return (
            bool(player_business.is_active)
            and player_business.business_id.lower() == "fruit_shop"
        )

    # Unknown role — deny.
    return False


def _get_player_business(player: Player, db: Session) -> PlayerBusiness | None:
    """Fetch the player's currently active business row, if any."""
    return (
        db.query(PlayerBusiness)
        .filter(
            PlayerBusiness.player_id == player.id,
            PlayerBusiness.is_active.is_(True),
        )
        .first()
    )


def _find_qualifying_role(
    player: Player,
    required_roles: list[str],
    already_filled: set[str],
    db: Session,
) -> str | None:
    """Return the first unfilled required role the player qualifies for.

    Iterates required_roles in order — first match wins (deterministic).
    Returns None if the player cannot fill any remaining role.
    """
    pb = _get_player_business(player, db)
    for role in required_roles:
        if role in already_filled:
            continue
        if player_qualifies_for_role(player, role, pb):
            return role
    return None


# ── Payout calculation ─────────────────────────────────────────────────────────


def calculate_deal_final_payout(
    template: DealTemplate,
    macro: MacroState,
    current_basket_prices: dict[str, float] | None = None,
) -> float:
    """Compute the macro-adjusted final payout for a deal.

    Formula:
      confidence_boost = ((consumer_confidence - 50) / 100) × confidence_sensitivity
      basket_pressure  = weighted mean of (price_index - 1.0) for each basket dep
                         (positive when prices are above baseline, negative below)
      multiplier       = clamp(1 + confidence_boost + basket_pressure, 0.80, 1.35)
      final_payout     = round(base_payout × multiplier, 2)

    basket_prices are expected as price_index values relative to a 1.0 baseline.
    Passing None for current_basket_prices skips the basket adjustment.

    The clamp [0.80, 1.35] prevents extreme payouts in either direction.
    Returns a float rounded to 2 decimal places.
    """
    base = float(template.base_payout_xgp)
    conf = float(macro.consumer_confidence)

    confidence_boost = (
        ((conf - 50.0) / 100.0) * float(template.confidence_sensitivity)
    )

    basket_pressure = 0.0
    if template.basket_dependency_json and current_basket_prices:
        deps: dict[str, float] = json.loads(template.basket_dependency_json)
        total_weight = sum(deps.values()) or 1.0
        for basket_id, weight in deps.items():
            # price_index: 1.0 = baseline; >1.0 = above baseline = higher payout.
            price_index = current_basket_prices.get(basket_id, 1.0)
            deviation = price_index - 1.0
            basket_pressure += (deviation * weight) / total_weight

    multiplier = 1.0 + confidence_boost + basket_pressure
    multiplier = max(0.80, min(1.35, multiplier))

    return float(_money(base * multiplier))


# ── Split validation ───────────────────────────────────────────────────────────


def validate_split_preset(
    required_roles: list[str],
    split_preset: list[float],
) -> tuple[bool, str | None]:
    """Validate a split preset array against the required roles list.

    Rules:
      - len(split_preset) must equal len(required_roles)
      - all values must be non-negative
      - values must sum to exactly 100 (within 0.01 tolerance)

    Returns (True, None) on success or (False, error_message) on failure.
    """
    if len(split_preset) != len(required_roles):
        return False, (
            f"Split preset has {len(split_preset)} value(s) but deal requires "
            f"{len(required_roles)} role(s)."
        )
    if any(s < 0 for s in split_preset):
        return False, "Split values must not be negative."
    total = sum(split_preset)
    if abs(total - 100.0) > 0.01:
        return False, f"Split values must sum to 100, got {total:.2f}."
    return True, None


# ── Create deal ────────────────────────────────────────────────────────────────


def create_coop_deal(
    db: Session,
    host_player: Player,
    template_id: str,
    split_preset: list[float],
) -> dict[str, Any]:
    """Host a new co-op deal against a system template.

    Flow:
    1. Fetch template; validate it is active.
    2. Validate split_preset length, values, and sum.
    3. Validate preset is one of template.allowed_split_presets_json.
    4. Host must qualify for at least one required role (deny-by-default).
    5. Create CoopDeal (status = "open", expires current_day + 1).
    6. Create CoopDealParticipant for the host with is_host=True.
    7. Commit atomically.

    The host is NOT paid at creation — payout only occurs after all roles are
    filled and complete_coop_deal() is called.

    Raises ValueError on any validation failure.
    """
    template = (
        db.query(DealTemplate)
        .filter(
            DealTemplate.template_id == template_id,
            DealTemplate.is_active.is_(True),
        )
        .first()
    )
    if template is None:
        raise ValueError(
            f"Template '{template_id}' not found or is not active. "
            "Call GET /deals/templates to see available templates."
        )

    required_roles: list[str] = json.loads(template.required_roles_json)
    allowed_presets: list[list[float]] = json.loads(template.allowed_split_presets_json)

    ok, err = validate_split_preset(required_roles, split_preset)
    if not ok:
        raise ValueError(err)

    # Ensure the chosen preset is one of the template's approved presets.
    if split_preset not in allowed_presets:
        raise ValueError(
            f"Split preset {split_preset} is not allowed for template '{template_id}'. "
            f"Allowed presets: {allowed_presets}."
        )

    # Host must qualify for at least one required role — no observer hosting.
    pb = _get_player_business(host_player, db)
    host_role: str | None = None
    for role in required_roles:
        if player_qualifies_for_role(host_player, role, pb):
            host_role = role
            break

    if host_role is None:
        raise ValueError(
            "You do not qualify for any required role in this deal. "
            f"Required roles: {required_roles}.  "
            f"Your main job: '{host_player.main_job}'. "
            "Make sure your job or active business matches a required role."
        )

    current_day = _current_day(db)
    deal = CoopDeal(
        template_id=template_id,
        display_name=template.display_name,
        host_player_id=str(host_player.id),
        status="open",
        required_roles_json=template.required_roles_json,
        assigned_split_json=json.dumps(split_preset),
        base_payout_xgp=template.base_payout_xgp,
        final_payout_xgp=0,
        hours_required_per_participant=template.hours_required_per_participant,
        region_bias=template.region_bias,
        created_day_number=current_day,
        expires_day_number=current_day + 1,
    )
    db.add(deal)
    db.flush()  # assign deal.id before creating participant

    # Host fills their first qualifying role; split index matches role position.
    host_role_index = required_roles.index(host_role)
    host_split = split_preset[host_role_index]
    db.add(CoopDealParticipant(
        deal_id=deal.id,
        player_id=host_player.id,
        role_id=host_role,
        split_percent=host_split,
        is_host=True,
        is_paid=False,
    ))
    db.commit()
    db.refresh(deal)

    roles_remaining = [r for r in required_roles if r != host_role]
    return {
        "message": "Co-op deal created.",
        "deal_id": deal.id,
        "template_id": template_id,
        "display_name": deal.display_name,
        "role_filled_by_host": host_role,
        "host_split_percent": host_split,
        "split_preset": split_preset,
        "required_roles": required_roles,
        "roles_remaining": roles_remaining,
        "participant_count": 1,
        "status": "open",
        "created_day_number": current_day,
        "expires_day_number": deal.expires_day_number,
    }


# ── Join deal ──────────────────────────────────────────────────────────────────


def join_coop_deal(
    db: Session,
    player: Player,
    deal_id: int,
) -> dict[str, Any]:
    """Join an open co-op deal in whichever unfilled role the player qualifies for.

    Flow:
    1. Fetch deal; validate status is "open".
    2. Validate deal has not expired against the current in-game day.
    3. Prevent duplicate participation (engine check + DB constraint backup).
    4. Find first unfilled required role the player qualifies for.
    5. Create CoopDealParticipant with matching split percent.
    6. If all roles are now filled, promote deal to "filled".
    7. Commit atomically.

    Raises ValueError on any validation failure.
    No duplicate participants are allowed.
    """
    deal = db.query(CoopDeal).filter(CoopDeal.id == deal_id).first()
    if deal is None:
        raise ValueError(f"Deal {deal_id} not found.")
    if deal.status != "open":
        raise ValueError(
            f"Deal {deal_id} is not open (status: '{deal.status}'). "
            "Only open deals can be joined."
        )

    current_day = _current_day(db)
    if deal.expires_day_number <= current_day:
        # Expire eagerly so future queries reflect correct status.
        deal.status = "expired"
        db.commit()
        raise ValueError(f"Deal {deal_id} has expired and is no longer accepting participants.")

    # Engine-level duplicate check (DB constraint is a second safety net).
    already_in = (
        db.query(CoopDealParticipant)
        .filter(
            CoopDealParticipant.deal_id == deal_id,
            CoopDealParticipant.player_id == player.id,
        )
        .first()
    )
    if already_in is not None:
        raise ValueError("You are already a participant in this deal.")

    required_roles: list[str] = json.loads(deal.required_roles_json)
    split_preset: list[float] = json.loads(deal.assigned_split_json)

    # Collect currently filled roles to determine what remains open.
    existing_participants = (
        db.query(CoopDealParticipant)
        .filter(CoopDealParticipant.deal_id == deal_id)
        .all()
    )
    already_filled_roles: set[str] = {p.role_id for p in existing_participants}

    qualifying_role = _find_qualifying_role(
        player, required_roles, already_filled_roles, db
    )
    if qualifying_role is None:
        unfilled = [r for r in required_roles if r not in already_filled_roles]
        raise ValueError(
            "You do not qualify for any remaining unfilled role in this deal. "
            f"Unfilled roles: {unfilled}.  "
            f"Your main job: '{player.main_job}'. "
            "Check that your job or active business matches a remaining role."
        )

    role_index = required_roles.index(qualifying_role)
    participant_split = split_preset[role_index]

    new_participant = CoopDealParticipant(
        deal_id=deal_id,
        player_id=player.id,
        role_id=qualifying_role,
        split_percent=participant_split,
        is_host=False,
        is_paid=False,
    )
    db.add(new_participant)
    db.flush()

    # Check whether all required roles are now filled.
    all_participants = existing_participants + [new_participant]
    filled_roles_now: set[str] = {p.role_id for p in all_participants}
    is_fully_filled = all(r in filled_roles_now for r in required_roles)

    if is_fully_filled:
        deal.status = "filled"

    db.commit()
    db.refresh(deal)

    return {
        "message": "Joined deal successfully.",
        "deal_id": deal_id,
        "display_name": deal.display_name,
        "role_assigned": qualifying_role,
        "split_percent": participant_split,
        "participant_count": len(all_participants),
        "required_roles": required_roles,
        "all_roles_filled": is_fully_filled,
        "status": deal.status,
    }


# ── Complete deal ──────────────────────────────────────────────────────────────


def complete_coop_deal(
    db: Session,
    deal_id: int,
) -> dict[str, Any]:
    """Complete a filled co-op deal and distribute XGP payout to all participants.

    Payout is atomic — either all participants are paid and the deal is marked
    completed, or an exception causes a full rollback with no partial state.

    Flow:
    1. Fetch deal; validate status == "filled".
    2. Fetch MacroState and DealTemplate for payout calculation.
    3. Calculate final_payout using calculate_deal_final_payout().
    4. For each participant:
       a. Compute share = final_payout × split_percent / 100.
       b. Capture balance_before; credit player.cash.
       c. Create CoopDealPayout (immutable audit row).
       d. Create XGPTransaction ("coop_deal_payout", direction="in").
       e. Create ContributionEvent ("co_op_deal") for PFT scoring.
       f. Increment player.reputation and successful_coop_deals_count.
       g. Mark participant is_paid = True.
    5. Update deal: status="completed", final_payout_xgp, completed_day_number.
    6. Commit atomically.

    Raises ValueError if deal is not in "filled" state.
    On any unexpected error, the transaction is rolled back and re-raised.
    """
    deal = db.query(CoopDeal).filter(CoopDeal.id == deal_id).first()
    if deal is None:
        raise ValueError(f"Deal {deal_id} not found.")
    if deal.status != "filled":
        raise ValueError(
            f"Deal {deal_id} cannot be completed (status: '{deal.status}'). "
            "Only 'filled' deals can be completed."
        )

    participants = (
        db.query(CoopDealParticipant)
        .filter(CoopDealParticipant.deal_id == deal_id)
        .all()
    )
    if not participants:
        raise ValueError(
            f"Deal {deal_id} has no participant records — data integrity issue."
        )

    current_day = _current_day(db)

    # Use the most recent active MacroState for payout calculation.
    macro = (
        db.query(MacroState)
        .filter(MacroState.is_active.is_(True))
        .order_by(MacroState.day_number.desc())
        .first()
    )
    template = (
        db.query(DealTemplate)
        .filter(DealTemplate.template_id == deal.template_id)
        .first()
    )

    if macro and template:
        final_payout = calculate_deal_final_payout(
            template, macro, current_basket_prices=None
        )
    else:
        # Fallback to base payout when macro or template is unavailable.
        final_payout = float(deal.base_payout_xgp)

    final_payout_d = _money(final_payout)
    payout_summary: list[dict] = []

    try:
        for participant in participants:
            player = (
                db.query(Player)
                .filter(Player.id == participant.player_id)
                .first()
            )
            if player is None:
                raise ValueError(
                    f"Player {participant.player_id} not found during payout. "
                    "Aborting to preserve economy integrity."
                )

            share = _money(
                final_payout_d
                * Decimal(str(participant.split_percent))
                / Decimal("100")
            )
            balance_before = _money(player.cash)
            player.cash = balance_before + share
            balance_after = _money(player.cash)

            # Immutable payout audit row — never mutated after creation.
            db.add(CoopDealPayout(
                deal_id=deal_id,
                player_id=player.id,
                split_percent=participant.split_percent,
                amount_xgp=share,
                balance_before=balance_before,
                balance_after=balance_after,
                day_number=current_day,
            ))

            # XGP ledger entry — part of the authoritative cash movement trail.
            db.add(XGPTransaction(
                player_id=player.id,
                transaction_type="coop_deal_payout",
                direction="in",
                amount=share,
                balance_before=balance_before,
                balance_after=balance_after,
                reference_type="coop_deal",
                reference_id=str(deal_id),
                description=f"Co-op deal payout: {deal.display_name}",
            ))

            # Contribution event — feeds the PFT reward scoring engine.
            metadata = json.dumps({
                "deal_id": deal_id,
                "template_id": deal.template_id,
                "role_id": participant.role_id,
                "split_percent": participant.split_percent,
                "day_number": current_day,
            })
            db.add(ContributionEvent(
                player_id=player.id,
                event_type="co_op_deal",
                xgp_value=float(share),
                event_units=1.0,
                metadata_json=metadata,
            ))

            # Modest trust signal — collaboration success increments reputation slowly.
            player.reputation = (player.reputation or 0) + 1
            player.successful_coop_deals_count = (
                (player.successful_coop_deals_count or 0) + 1
            )
            participant.is_paid = True

            payout_summary.append({
                "player_id": str(player.id),
                "role_id": participant.role_id,
                "split_percent": participant.split_percent,
                "amount_xgp": float(share),
                "balance_after": float(balance_after),
            })

        deal.status = "completed"
        deal.final_payout_xgp = final_payout_d
        deal.completed_day_number = current_day
        db.commit()

    except Exception:
        db.rollback()
        raise

    return {
        "message": "Co-op deal completed. Payout distributed to all participants.",
        "deal_id": deal_id,
        "template_id": deal.template_id,
        "display_name": deal.display_name,
        "final_payout_xgp": float(final_payout_d),
        "participant_payouts": payout_summary,
        "completed_day_number": current_day,
        "status": "completed",
    }


# ── Expire stale deals ─────────────────────────────────────────────────────────


def expire_open_deals(db: Session, current_day_number: int) -> int:
    """Expire all open deals whose expires_day_number <= current_day_number.

    For each expired deal:
    - Sets status = "expired".
    - Increments host.failed_coop_deals_count (signals collaboration failure).

    No goods or money are moved — expiration is a status-only operation.
    Safe and idempotent to call repeatedly (already-expired deals are skipped
    by the status == "open" filter).

    Returns the count of deals that were just expired.
    """
    stale = (
        db.query(CoopDeal)
        .filter(
            CoopDeal.status == "open",
            CoopDeal.expires_day_number <= current_day_number,
        )
        .all()
    )

    for deal in stale:
        deal.status = "expired"
        if deal.host_player_id:
            host = (
                db.query(Player)
                .filter(Player.id == deal.host_player_id)
                .first()
            )
            if host is not None:
                host.failed_coop_deals_count = (
                    (host.failed_coop_deals_count or 0) + 1
                )

    if stale:
        db.commit()

    return len(stale)


# ── Player summary ─────────────────────────────────────────────────────────────


def build_deals_summary(db: Session, player: Player) -> dict[str, Any]:
    """Return a player's co-op deal profile summary.

    Includes:
    - Active deals hosted (open or filled)
    - Active deals joined (as non-host participant; open or filled)
    - Lifetime successful and failed deal counts
    - Current reputation score
    """
    active_hosted = (
        db.query(CoopDeal)
        .filter(
            CoopDeal.host_player_id == str(player.id),
            CoopDeal.status.in_(["open", "filled"]),
        )
        .count()
    )

    # Deals where the player is a non-host participant that are still active.
    joined_participations = (
        db.query(CoopDealParticipant)
        .filter(
            CoopDealParticipant.player_id == player.id,
            CoopDealParticipant.is_host.is_(False),
        )
        .all()
    )
    joined_deal_ids = [p.deal_id for p in joined_participations]
    active_joined = 0
    if joined_deal_ids:
        active_joined = (
            db.query(CoopDeal)
            .filter(
                CoopDeal.id.in_(joined_deal_ids),
                CoopDeal.status.in_(["open", "filled"]),
            )
            .count()
        )

    return {
        "player_id": str(player.id),
        "active_deals_hosted": active_hosted,
        "active_deals_joined": active_joined,
        "successful_coop_deals_count": player.successful_coop_deals_count or 0,
        "failed_coop_deals_count": player.failed_coop_deals_count or 0,
        "reputation": player.reputation or 0,
    }
