"""app/models/job_opening.py — Step 14: Firm job opening listings.

JobOpening rows represent available wage-labor positions generated by firms.
In Step 14, all openings are NPC-generated and observable via the internal API.
Players will be able to apply for these in a future hiring step.

source_type determines the economic context:
  "npc_market"      — standard NPC firm position (most common)
  "player_firm"     — player-owned business vacancy (future)
  "public_contract" — system-level gig (e.g. regional delivery contract)

slots_total / slots_filled: multiple identical positions can share one row.
  A row becomes "filled" when slots_filled >= slots_total.
  A row becomes "expired" when expires_day is reached with slots remaining.

demand_multiplier: adjusts the effective wage relative to the market rate.
  > 1.0 → employer bidding above market (urgent / high-value).
  < 1.0 → below market (easy fill / firm under cash pressure).
"""

from sqlalchemy import Column, DateTime, ForeignKey, Integer, Numeric, String, func

from app.db.database import Base


class JobOpening(Base):
    """A wage-labor vacancy posted by a firm or the market system."""

    __tablename__ = "job_openings"

    # Integer PK — consistent with Firm for ergonomic API usage.
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Null = public_contract with no specific employer.
    firm_id = Column(Integer, ForeignKey("firms.id", ondelete="SET NULL"), nullable=True, index=True)

    # Region where the position is based.
    region = Column(String(40), nullable=False, index=True)

    # Role string — matches player.main_job values and deal role identifiers.
    # e.g. "chef" / "delivery_driver" / "auto_mechanic" / "retail_worker"
    job_type = Column(String(60), nullable=False, index=True)

    # How many identical positions exist in this posting.
    slots_total = Column(Integer, nullable=False, default=1)
    slots_filled = Column(Integer, nullable=False, default=0)

    # Daily wage offered per worker (XGP).
    wage_offer_xgp = Column(Numeric(10, 2), nullable=False, default=0.0)

    # Multiplier applied on top of the base wage by macro / firm policy.
    demand_multiplier = Column(Numeric(8, 4), nullable=False, default=1.0)

    # "npc_market" / "player_firm" / "public_contract"
    source_type = Column(String(30), nullable=False, default="npc_market")

    # "open" / "filled" / "expired" / "cancelled"
    status = Column(String(20), nullable=False, default="open", index=True)

    # In-game day the opening was created.
    created_day = Column(Integer, nullable=False, default=1)

    # In-game day the opening expires if not filled.  Null = no expiry.
    expires_day = Column(Integer, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
