"""app/core/contribution_rules.py — Weighted contribution scoring rules.

These weights determine how each type of in-game activity translates into a
player's monthly contribution score.  A higher score means a larger share of
the monthly PFT reward pool.

Tuning notes
------------
* All weights below are PLACEHOLDERS for Season 1.  They should be reviewed
  after the first live epoch once real player distribution data is available.
* Positive weights reward behaviour that adds value to the economy (work,
  trade, co-operation, reputation building).
* The penalty weight is negative — bad behaviour directly reduces the score
  instead of just gating eligibility.
* The engine clamps the final score at 0 so penalties cannot produce a
  negative allocation.
"""

CONTRIBUTION_WEIGHTS: dict = {
    # XGP earned through main-job / side-job work.
    # Direct labour income: the backbone of the gameplay economy.
    "job_work": 1.0,

    # XGP profit generated by owned businesses.
    # Lower weight than direct work to avoid passive-income dominance.
    "business_profit": 0.5,

    # Volume of XGP traded on the marketplace.
    # Rewards liquidity provision and price discovery.
    "market_trade": 0.3,

    # Number of co-operative deals completed with other players.
    # Multiplied by a unit value in the engine (e.g. × 100 XGP equivalent).
    # Highest per-unit weight to encourage player-vs-player collaboration.
    "co_op_deal": 1.2,

    # Reputation points added to the weighted total as a small bonus.
    # Rewards long-term trustworthy behaviour.
    "reputation_bonus": 0.2,

    # Deduction applied for each penalty point accumulated.
    # Negative value: engine subtracts abs(weight) × penalty_points.
    # NOTE: keep this value negative so the engine formula is unambiguous.
    "penalty_for_bad_behavior": -2.0,
}
